INSERT INTO roles (name) VALUES
('SUPER_ADMIN'), ('CATALOG_MANAGER'), ('ORDER_MANAGER')
ON CONFLICT (name) DO NOTHING;

INSERT INTO permissions (name) VALUES
('PRODUCT_VIEW'), ('PRODUCT_CREATE'), ('PRODUCT_UPDATE'), ('PRODUCT_DELETE'),
('CATEGORY_VIEW'), ('CATEGORY_CREATE'), ('CATEGORY_UPDATE'), ('CATEGORY_DELETE'),
('ORDER_VIEW'), ('ORDER_UPDATE'), ('ORDER_CANCEL'),
('CUSTOMER_VIEW'), ('CUSTOMER_UPDATE'), ('CUSTOMER_BLOCK'),
('INVENTORY_VIEW'), ('INVENTORY_UPDATE'), ('DASHBOARD_VIEW'),
('PAYMENT_VIEW'), ('REFUND_CREATE'),
('COUPON_VIEW'), ('COUPON_CREATE'), ('COUPON_UPDATE'), ('COUPON_DELETE'),
('REVIEW_MODERATE'), ('USER_MANAGE'), ('ROLE_MANAGE')
ON CONFLICT (name) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u JOIN roles r ON r.name = u.role::text
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'SUPER_ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON p.name IN
('PRODUCT_VIEW','PRODUCT_CREATE','PRODUCT_UPDATE','PRODUCT_DELETE',
'CATEGORY_VIEW','CATEGORY_CREATE','CATEGORY_UPDATE','CATEGORY_DELETE',
'ORDER_VIEW','ORDER_UPDATE','ORDER_CANCEL','CUSTOMER_VIEW','CUSTOMER_UPDATE',
'CUSTOMER_BLOCK','INVENTORY_VIEW','INVENTORY_UPDATE','DASHBOARD_VIEW',
'PAYMENT_VIEW','REFUND_CREATE','COUPON_VIEW','COUPON_CREATE','COUPON_UPDATE',
'COUPON_DELETE','REVIEW_MODERATE','USER_MANAGE')
WHERE r.name = 'ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON p.name IN
('PRODUCT_VIEW','PRODUCT_CREATE','PRODUCT_UPDATE','PRODUCT_DELETE',
'CATEGORY_VIEW','CATEGORY_CREATE','CATEGORY_UPDATE','CATEGORY_DELETE','INVENTORY_VIEW')
WHERE r.name = 'CATALOG_MANAGER'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON p.name IN
('ORDER_VIEW','ORDER_UPDATE','ORDER_CANCEL','CUSTOMER_VIEW','PAYMENT_VIEW')
WHERE r.name = 'ORDER_MANAGER'
ON CONFLICT DO NOTHING;
