ALTER TABLE carts ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE carts ADD COLUMN IF NOT EXISTS guest_token VARCHAR(128);
CREATE UNIQUE INDEX IF NOT EXISTS ux_carts_guest_token ON carts(guest_token);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_code VARCHAR(80);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS currency VARCHAR(3) NOT NULL DEFAULT 'INR';
CREATE TABLE IF NOT EXISTS coupons (
 id BIGSERIAL PRIMARY KEY, code VARCHAR(80) NOT NULL UNIQUE, discount_type VARCHAR(20) NOT NULL,
 discount_value NUMERIC(12,2) NOT NULL, minimum_order_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
 maximum_discount_amount NUMERIC(12,2), usage_limit INTEGER, used_count INTEGER NOT NULL DEFAULT 0,
 per_customer_limit INTEGER NOT NULL DEFAULT 1, active BOOLEAN NOT NULL DEFAULT TRUE,
 starts_at TIMESTAMPTZ, expires_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS coupon_usages (
 id BIGSERIAL PRIMARY KEY, coupon_id BIGINT NOT NULL REFERENCES coupons(id), user_id BIGINT REFERENCES users(id),
 order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id), used_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(coupon_id,user_id)
);
CREATE TABLE IF NOT EXISTS payments (
 id BIGSERIAL PRIMARY KEY, order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id), provider VARCHAR(40) NOT NULL,
 provider_payment_id VARCHAR(160), amount NUMERIC(12,2) NOT NULL, status VARCHAR(30) NOT NULL,
 idempotency_key VARCHAR(160) NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS payment_events (
 id BIGSERIAL PRIMARY KEY, provider VARCHAR(40) NOT NULL, event_id VARCHAR(160) NOT NULL UNIQUE,
 payload TEXT, received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS shipments (
 id BIGSERIAL PRIMARY KEY, order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id), carrier VARCHAR(100),
 tracking_number VARCHAR(160), status VARCHAR(30) NOT NULL DEFAULT 'PENDING', shipped_at TIMESTAMPTZ,
 delivered_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS returns (
 id BIGSERIAL PRIMARY KEY, order_id BIGINT NOT NULL REFERENCES orders(id), user_id BIGINT NOT NULL REFERENCES users(id),
 reason VARCHAR(500) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'REQUESTED', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(order_id)
);
CREATE TABLE IF NOT EXISTS order_status_history (
 id BIGSERIAL PRIMARY KEY, order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
 from_status VARCHAR(30), to_status VARCHAR(30) NOT NULL, note VARCHAR(500), changed_by BIGINT REFERENCES users(id),
 changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS reviews (
 id BIGSERIAL PRIMARY KEY, product_id BIGINT NOT NULL REFERENCES products(id), user_id BIGINT NOT NULL REFERENCES users(id),
 order_id BIGINT REFERENCES orders(id), rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5), title VARCHAR(200),
 body TEXT, status VARCHAR(30) NOT NULL DEFAULT 'PENDING', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(product_id,user_id,order_id)
);
