package com.sathavahana.kalamkari.service;

import com.sathavahana.kalamkari.domain.*;
import com.sathavahana.kalamkari.dto.AdminDto.*;
import com.sathavahana.kalamkari.repository.*;
import org.springframework.data.domain.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.util.*;

@Service
public class AdminOperationsService {
 private final ProductRepository products; private final CategoryRepository categories; private final UserRepository users;
 private final OrderRepository orders; private final CurrentUser current; private final JdbcTemplate jdbc;
 public AdminOperationsService(ProductRepository p,CategoryRepository c,UserRepository u,OrderRepository o,CurrentUser cu,JdbcTemplate j){products=p;categories=c;users=u;orders=o;current=cu;jdbc=j;}
 private User actor(){return current.require();}
 private void audit(String action,String type,Object id,String details){jdbc.update("insert into audit_logs(actor_id,action,resource_type,resource_id,details) values(?,?,?,?,?)",actor().getId(),action,type,String.valueOf(id),details);}
 private ProductView product(Product p){return new ProductView(p.getId(),p.getSlug(),p.getName(),p.getDescription(),p.getPrice(),p.getStockQuantity(),p.getCategory()==null?null:p.getCategory().getId(),p.getImageUrl(),p.isActive());}
 @Transactional(readOnly=true) public Dashboard dashboard(){long cust=users.countByRole(User.Role.CUSTOMER); long ord=orders.count(); BigDecimal revenue=orders.findAll().stream().filter(o->o.getStatus()!=Order.Status.CANCELLED).map(Order::getTotalAmount).reduce(BigDecimal.ZERO,BigDecimal::add);return new Dashboard(products.count(),products.countByActiveTrue(),cust,ord,orders.countByStatus(Order.Status.PENDING),revenue);}
 @Transactional(readOnly=true) public Page<ProductView> productSearch(String q,Pageable page){String term=q==null?"":q;return products.findByNameContainingIgnoreCaseOrSlugContainingIgnoreCase(term,term,page).map(this::product);}
 @Transactional public ProductView createProduct(ProductInput in){if(in==null||in.slug()==null||in.name()==null||in.price()==null||in.price().signum()<0)throw new IllegalArgumentException("slug, name and non-negative price are required"); Product p=new Product();p.setSlug(in.slug());p.setName(in.name());p.setDescription(in.description());p.setPrice(in.price());p.setStockQuantity(Math.max(0,in.stockQuantity()==null?0:in.stockQuantity()));p.setImageUrl(in.imageUrl());p.setActive(in.active()==null||in.active());if(in.categoryId()!=null)p.setCategory(categories.findById(in.categoryId()).orElseThrow(()->new NotFoundException("Category not found")));p=products.save(p);audit("CREATE","PRODUCT",p.getId(),p.getSlug());return product(p);}
 @Transactional public ProductView updateProduct(Long id,ProductInput in){Product p=products.findById(id).orElseThrow(()->new NotFoundException("Product not found"));if(in.slug()!=null)p.setSlug(in.slug());if(in.name()!=null)p.setName(in.name());if(in.description()!=null)p.setDescription(in.description());if(in.price()!=null){if(in.price().signum()<0)throw new IllegalArgumentException("Price cannot be negative");p.setPrice(in.price());}if(in.stockQuantity()!=null){if(in.stockQuantity()<0)throw new IllegalArgumentException("Stock cannot be negative");p.setStockQuantity(in.stockQuantity());}if(in.imageUrl()!=null)p.setImageUrl(in.imageUrl());if(in.active()!=null)p.setActive(in.active());if(in.categoryId()!=null)p.setCategory(categories.findById(in.categoryId()).orElseThrow(()->new NotFoundException("Category not found")));audit("UPDATE","PRODUCT",id,"");return product(p);}
 @Transactional public void deleteProduct(Long id){Product p=products.findById(id).orElseThrow(()->new NotFoundException("Product not found"));p.setActive(false);audit("ARCHIVE","PRODUCT",id,"");}
 private CategoryView category(Category c){return new CategoryView(c.getId(),c.getSlug(),c.getName(),c.getDescription(),c.isArchived());}
 @Transactional(readOnly=true) public List<CategoryView> categoryList(){return categories.findAll().stream().map(this::category).toList();}
 @Transactional public CategoryView createCategory(CategoryInput in){if(in==null||in.slug()==null||in.name()==null)throw new IllegalArgumentException("slug and name are required");Category c=new Category(in.slug(),in.name(),in.description());c=categories.save(c);audit("CREATE","CATEGORY",c.getId(),c.getSlug());return category(c);}
 @Transactional public CategoryView updateCategory(Long id,CategoryInput in){Category c=categories.findById(id).orElseThrow(()->new NotFoundException("Category not found"));if(in.slug()!=null)c.setSlug(in.slug());if(in.name()!=null)c.setName(in.name());if(in.description()!=null)c.setDescription(in.description());audit("UPDATE","CATEGORY",id,"");return category(c);}
 @Transactional public void archiveCategory(Long id){Category c=categories.findById(id).orElseThrow(()->new NotFoundException("Category not found"));c.setArchived(true);audit("ARCHIVE","CATEGORY",id,"");}
 @Transactional(readOnly=true) public List<InventoryTransaction> inventory(){return jdbc.query("select id,product_id,quantity_delta,reason,created_by,created_at from inventory_transactions order by created_at desc", (r,n)->new InventoryTransaction(r.getLong(1),r.getLong(2),r.getInt(3),r.getString(4),(Long)r.getObject(5),r.getTimestamp(6).toInstant()));}
 @Transactional public InventoryTransaction adjust(Long productId,InventoryAdjustment in){if(in==null||in.quantityDelta()==0||in.reason()==null||in.reason().isBlank())throw new IllegalArgumentException("A non-zero quantity and reason are required");Product p=products.findLocked(productId).orElseThrow(()->new NotFoundException("Product not found"));int next=p.getStockQuantity()+in.quantityDelta();if(next<0)throw new IllegalArgumentException("Inventory cannot become negative");p.setStockQuantity(next);Long uid=actor().getId();jdbc.update("insert into inventory_transactions(product_id,quantity_delta,reason,created_by) values(?,?,?,?)",productId,in.quantityDelta(),in.reason(),uid);audit("ADJUST","INVENTORY",productId,in.reason());return jdbc.queryForObject("select id,product_id,quantity_delta,reason,created_by,created_at from inventory_transactions where id=(select max(id) from inventory_transactions)",(r,n)->new InventoryTransaction(r.getLong(1),r.getLong(2),r.getInt(3),r.getString(4),(Long)r.getObject(5),r.getTimestamp(6).toInstant()));}
 @Transactional(readOnly=true) public Page<CustomerView> customers(String q,Pageable page){String t=q==null?"":q;return users.findByEmailContainingIgnoreCaseOrFirstNameContainingIgnoreCaseOrLastNameContainingIgnoreCase(t,t,t,page).map(u->new CustomerView(u.getId(),u.getEmail(),u.getFirstName(),u.getLastName(),u.getPhone(),u.getRole(),u.getStatus(),u.getCreatedAt()));}
 @Transactional(readOnly=true) public CustomerView customer(Long id){User u=users.findById(id).orElseThrow(()->new NotFoundException("Customer not found"));return new CustomerView(u.getId(),u.getEmail(),u.getFirstName(),u.getLastName(),u.getPhone(),u.getRole(),u.getStatus(),u.getCreatedAt());}
 @Transactional public CustomerView customerStatus(Long id,StatusChange s){User u=users.findById(id).orElseThrow(()->new NotFoundException("Customer not found"));try{u.setStatus(User.Status.valueOf(s.status().toUpperCase()));}catch(Exception e){throw new IllegalArgumentException("Invalid customer status");}audit("STATUS","CUSTOMER",id,s.note());return customer(id);}
 @Transactional(readOnly=true) public Page<OrderView> orderList(Pageable page){return orders.findAllByOrderByCreatedAtDesc(page).map(this::order);}
 private OrderView order(Order o){return new OrderView(o.getId(),o.getUser().getId(),o.getUser().getEmail(),o.getStatus(),o.getPaymentStatus(),o.getTotalAmount(),o.getCreatedAt());}
 @Transactional(readOnly=true) public OrderView order(Long id){return order(orders.findById(id).orElseThrow(()->new NotFoundException("Order not found")));}
 @Transactional public OrderView orderStatus(Long id,StatusChange s){Order o=orders.findById(id).orElseThrow(()->new NotFoundException("Order not found"));Order.Status from=o.getStatus(),to;try{to=Order.Status.valueOf(s.status().toUpperCase());}catch(Exception e){throw new IllegalArgumentException("Invalid order status");}if(from==to)throw new IllegalArgumentException("Order is already in that status");if(from==Order.Status.CANCELLED||from==Order.Status.DELIVERED||(to==Order.Status.SHIPPED&&from!=Order.Status.CONFIRMED)||(to==Order.Status.DELIVERED&&from!=Order.Status.SHIPPED))throw new IllegalArgumentException("Invalid order status transition");o.setStatus(to);jdbc.update("insert into order_status_history(order_id,from_status,to_status,changed_by,note) values(?,?,?,?,?)",id,from.name(),to.name(),actor().getId(),s.note());audit("STATUS","ORDER",id,s.note());return order(o);}
 @Transactional(readOnly=true) public List<OrderHistory> orderHistory(Long id){return jdbc.query("select id,order_id,from_status,to_status,changed_by,note,created_at from order_status_history where order_id=? order by created_at",new Object[]{id},(r,n)->new OrderHistory(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),(Long)r.getObject(5),r.getString(6),r.getTimestamp(7).toInstant()));}
 @Transactional(readOnly=true) public List<AuditView> audits(Pageable page){return jdbc.query("select id,actor_id,action,resource_type,resource_id,details,created_at from audit_logs order by created_at desc limit ? offset ?",(r,n)->new AuditView(r.getLong(1),(Long)r.getObject(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getTimestamp(7).toInstant()),page.getPageSize(),page.getOffset());}
 @Transactional(readOnly=true) public List<SettingView> settings(){return jdbc.query("select setting_key,setting_value,updated_at from admin_settings order by setting_key",(r,n)->new SettingView(r.getString(1),r.getString(2),r.getTimestamp(3).toInstant()));}
 @Transactional public SettingView setting(String key,SettingInput in){if(key==null||key.isBlank()||in==null||in.value()==null)throw new IllegalArgumentException("Setting key and value are required");jdbc.update("insert into admin_settings(setting_key,setting_value,updated_by,updated_at) values(?,?,?,CURRENT_TIMESTAMP) on conflict (setting_key) do update set setting_value=excluded.setting_value,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP",key,in.value(),actor().getId());audit("UPDATE","SETTING",key,"");return settings().stream().filter(s->s.key().equals(key)).findFirst().orElseThrow();}
 @Transactional(readOnly=true) public Report report(String period){return new Report(period==null?"all":period,orders.count(),orders.findAll().stream().filter(o->o.getStatus()!=Order.Status.CANCELLED).map(Order::getTotalAmount).reduce(BigDecimal.ZERO,BigDecimal::add),Map.of("PENDING",orders.countByStatus(Order.Status.PENDING),"CONFIRMED",orders.countByStatus(Order.Status.CONFIRMED),"SHIPPED",orders.countByStatus(Order.Status.SHIPPED),"DELIVERED",orders.countByStatus(Order.Status.DELIVERED),"CANCELLED",orders.countByStatus(Order.Status.CANCELLED)));}
}
